version: "3.9"
services:
  poc-intercepeter-api:
      build: 
        context: .
        dockerfile: ./poc-intercepeter-api/Dockerfile
      image: ${DOCKER_REGISTRY-}pocintercepeterapi
      networks:
        - poc-sed
      depends_on:
        - mongodb

  poc-intercepeter-api-bv:
      build: 
        context: .
        dockerfile: ./poc-intercepeter-api-bv/Dockerfile
      image: ${DOCKER_REGISTRY-}pocintercepeterapibv
      networks:
        - poc-sed

  poc-intercepeter-grpc:
    build: 
      context: .
      dockerfile: ./poc-intercepeter-grpc/Dockerfile
    image: ${DOCKER_REGISTRY-}pocintercepeteragrpc
    networks:
      - poc-sed
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin-basic
      - ME_CONFIG_BASICAUTH_PASSWORD=pw-basic
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    volumes:
      - mongodb-data
    networks:
      - poc-sed
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin-basic:pw-basic@localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - poc-sed
    volumes:   
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data

networks: 
    poc-sed:
      driver: bridge